CREATE TABLE [USERS] (
   [USERCODE]       INTEGER          NOT NULL    IDENTITY(1,1),
   [EMAIL]          NVARCHAR(100)    NOT NULL    UNIQUE,
   [NAME]           NVARCHAR(100)    NOT NULL,
   [PASSWORD]       NVARCHAR(100)    NULL,
   [STATUSCODE]     INTEGER          NOT NULL,
   [CRATEDATE]      DATETIME         NOT NULL,
   [LASTUPDATE]     DATETIME         NOT NULL,
   [PICTUREPATH]    NVARCHAR(255)    NULL,
   CONSTRAINT PK_USER PRIMARY KEY ([USERCODE])
)
GO

CREATE TABLE [USER_STATUS] (
   [STATUSCODE]    INTEGER         NOT NULL    IDENTITY(1,1),
   [NAME]          NVARCHAR(20)    NOT NULL,
   CONSTRAINT PK_USER_STAUS PRIMARY KEY ([STATUSCODE])
)
GO

ALTER TABLE [USERS]
   ADD CONSTRAINT FK_USERS_REF_USER_STATUS FOREIGN KEY ([STATUSCODE])
      REFERENCES [USER_STATUS] ([STATUSCODE])
GO
